
Turn 2
================================================================
error: failed to decode bot message: "T" (at position 1)
Last input received was:
Traceback (most recent call last):
  File "MyBot.py", line 154, in <module>
    handleShipAI(ship)
  File "MyBot.py", line 47, in handleShipAI
    logging.info(quadrant)
NameError: name 'quadrant' is not defined

